import { formatSGD } from '@/lib/insure/engine/scorer'

const printStyles = {
  page: { fontFamily: 'Georgia, serif', color: '#111', maxWidth: '680px' },
  h1: { fontSize: '22px', margin: '0 0 4px' },
  meta: { fontSize: '12px', color: '#555', margin: '0 0 20px' },
  scoreLine: { fontSize: '16px', fontWeight: 'bold', margin: '0 0 4px' },
  section: { marginTop: '20px' },
  sectionTitle: { fontSize: '14px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '0.04em', margin: '0 0 8px', borderBottom: '1px solid #999', paddingBottom: '4px' },
  row: { display: 'flex', justifyContent: 'space-between', fontSize: '13px', padding: '4px 0', borderBottom: '1px solid #eee' },
  planItem: { fontSize: '13px', margin: '0 0 10px', pageBreakInside: 'avoid' },
  checkbox: { display: 'inline-block', width: '11px', height: '11px', border: '1px solid #333', marginRight: '8px', verticalAlign: 'middle' },
  disclaimer: { fontSize: '10px', color: '#777', marginTop: '28px', lineHeight: 1.5, borderTop: '1px solid #999', paddingTop: '10px' },
}

export default function PrintSummary({ result, gaps, actionPlan }) {
  const generatedDate = new Date().toLocaleDateString('en-SG', { year: 'numeric', month: 'long', day: 'numeric' })
  const { hosp, resilience, life, premium, di } = result.pillars

  return (
    <div className="print-summary" style={printStyles.page}>
      <h1 style={printStyles.h1}>InsureCheck — Insurance Score Summary</h1>
      <p style={printStyles.meta}>Generated {generatedDate} · Educational tool, not financial advice · coah.sg</p>

      <p style={printStyles.scoreLine}>
        Score: {result.finalScore}/100 — {result.band.label}{result.isEstimated ? ' (estimated)' : ''}
      </p>

      <div style={printStyles.section}>
        <p style={printStyles.sectionTitle}>Coverage breakdown</p>
        <div style={printStyles.row}>
          <span>Hospitalisation</span>
          <span>{hosp.passed ? 'Covered' : hosp.isUnsure ? 'Not sure' : 'Not covered'}</span>
        </div>
        <div style={printStyles.row}>
          <span>Critical illness</span>
          <span>{formatSGD(resilience.ci.amount)} of {formatSGD(resilience.ci.target)} target ({resilience.ci.score}/100)</span>
        </div>
        <div style={printStyles.row}>
          <span>Life / TPD</span>
          <span>{formatSGD(life.amount)} of {formatSGD(life.target)} target ({life.score}/100)</span>
        </div>
        <div style={printStyles.row}>
          <span>Premium efficiency</span>
          <span>{premium.score === null ? 'Not provided' : `${(premium.ratio * 100).toFixed(1)}% of income (${premium.score}/100)`}</span>
        </div>
        {di.score !== null && (
          <div style={printStyles.row}>
            <span>Disability income (not included in score above)</span>
            <span>{formatSGD(di.amount)}/mo of {formatSGD(di.target)}/mo target ({di.score}/100)</span>
          </div>
        )}
      </div>

      {gaps.some(g => g.direction !== 'ok') && (
        <div style={printStyles.section}>
          <p style={printStyles.sectionTitle}>Your gap in numbers</p>
          {gaps.filter(g => g.direction !== 'ok').map(gap => (
            <div key={gap.id} style={printStyles.row}>
              <span>{gap.label}</span>
              <span>{gap.direction === 'under' ? 'Short by' : 'Above target by'} {formatSGD(gap.amount)}</span>
            </div>
          ))}
        </div>
      )}

      {actionPlan.length > 0 && (
        <div style={printStyles.section}>
          <p style={printStyles.sectionTitle}>Action plan</p>
          {actionPlan.map(item => (
            <div key={item.id} style={printStyles.planItem}>
              <p style={{ margin: '0 0 2px' }}>
                <span style={printStyles.checkbox} />
                <strong>{item.title}</strong>
              </p>
              <p style={{ margin: '0 0 2px 19px', color: '#333' }}>{item.detail}</p>
              {item.ask && (
                <p style={{ margin: '0 0 0 19px', fontStyle: 'italic', color: '#555' }}>
                  Ask your adviser: &quot;{item.ask}&quot;
                </p>
              )}
            </div>
          ))}
        </div>
      )}

      <p style={printStyles.disclaimer}>
        This score is for educational purposes only and does not constitute financial advice.
        Coverage benchmarks are based on general Singapore financial planning guidelines. Please
        consult a MAS-licensed financial adviser for personal recommendations. Not affiliated
        with any insurer or MAS-licensed entity. Generated by InsureCheck, a nat does the math project.
      </p>
    </div>
  )
}
